### ISSUE TITLE
tpmclient tests don't pass when run against 1.36 simulator

### ISSUE THREAD

**Issue by wcarthur1** [01org/tpm2-tss#285]
In a couple cases, the simulator returns TPM_RC_RETRY.  This just means that the command needs to be retried.  I've fixed it on my local version of tpmclient.  When I get a chance, I'll create a pull request for this.

**Comment by flihp** [comment]
resolved in #522

**Comment by flihp** [comment]
whoops, forgot to close this when we merged #522
