### ISSUE TITLE
Sample code for authorization policy

### ISSUE THREAD

**Issue by danglus** [01org/tpm2-tss#399]
Hi,
   I'm trying to figure out how to create and use an authorization policy for an RSA key. Anyway, reading the standard and the 'practical guide' book left me with many questions.
Anyway, can anyone point me to relevant code sample?
       
       Thanks,
Dan

**Comment by flihp** [comment]
I know the feeling Dan. Unfortunately the only thing close to what you're looking for here is still tangled up in the tpmclient test code. If you provide some details about the policy you're looking to create maybe we can hash something out here.

**Comment by danglus** [comment]
@flihp I managed to do the whole duplication procedure (including an authorization policy), and copy an RSA key from one TPM to the other.  It is a a long sequence (something like 14 steps) and I created 10 independent, low level, executables to support it. The execs all connect directly to the driver at '/dev/tpm0', and I only tested it with the Infineon 9665 TPM that is installed on the NUCs that I have.

I can do some cleanups, create a readme file, and do a pull request to add it to the samples directory.
  What do you think?

**Comment by flihp** [comment]
First off: I think this is one hell of an accomplishment :) I've been working with this code base for ~6 months now and while I can now tell you all about how C structures are transformed into TPM command buffers (and vise-versa) I know very little about how to actually *use* the TPM. If nothing else I'm looking forward to reading your code to understand how this process actually works.

Now where this code should live is an interesting question. I think the best end result would be to turn it into a 'tool' and get it integrated into the tpm2.0-tools project. Any chance I can get you to put this code up somewhere public so I can take a look? Something like what @dguerri did for this work with the tools stuff he did last year:
 https://dguerriblog.wordpress.com/2016/03/03/tpm2-0-and-openssl-on-linux-2/

**Comment by williamcroberts** [comment]
I pretty much have the save statement as @flihp. I'd love to see a tool around this key migration that makes it easy. I'm not sure offhand what the tool granularity should be, and or what tools need modification or adding offhand. Because like @flihp, my understanding of the tpm is even more limited.

**Comment by danglus** [comment]
@flihp, for worth, I can show you what I did (and why) in an online web-conf. 

Question: Looking at the 'practical guide' TPM book credits, I see that two of the authors are from Intel.  Any change you could arrange a Q&A session with them?

**Comment by flihp** [comment]
I only know of one author from Intel (@wcarthur1) who has since left.. Who's the other one?

**Comment by danglus** [comment]
The other author is Monty Wiseman.
According to his linked-in profile he is also not working for intel anymore…

**Comment by flihp** [comment]
Didn't realize he was listed as an author. He's not listed on the books website: http://www.apress.com/us/book/9781430265832. Neither of them work for Intel any longer unfortunately.
