### ISSUE TITLE
How to save key generated by TPM in external storeage

### ISSUE THREAD

**Issue by khanhnt93** [01org/tpm2-tss#430]
In TPM spec, they said TPM has limited memory so TPM must save encrypted object to external storeage. But when I use encrypt function of TPM, TPM just save object by context file and context file can't load after TPM reset/shutdown, so I just use a key in limited times.
In case I want to use a key for many times, how can I do that?

**Comment by crogers1** [comment]
CreatePrimary creates a transient handle which does not survive TPM reset or shutdown.  In this case, you can either call CreatePrimary again with the same options to derive the same handle to decrypt your data, or you call Tpm_EvictControl to make the transient handle a persistent handle and use that for decryption.  The persistent handle will remain valid across shutdown/reset.  To get rid of a persistent handle, use EvictControl again or use Tpm_Clear.

**Comment by khanhnt93** [comment]
Because memory of TPM limited, in case I have many task need crypto, so make transient handle a persistent handle not good. Can you explain more about call CreatePrimary again? There is no secret input option in CreatePrimary.

**Comment by danglus** [comment]
1)  Can you explain why you can't use a single primary-key? TPM2.0 allow you to create a whole hierarchy of keys under a single primary-key. 
2)  Unlike regular asymmetrical keys, that are created with the TPM random number generator, the primary keys are created from the TPM 'seed' using a Key derivation function. Hence, calling TPM2_CreatePrimary twice, with the same parameters, will yield the same key (while doing the same for TPM2_Create will create totally different keys).
3) TPM2_CreatePrimary  has a TPM2B_SENSITIVE_CREATE inSensitive input parameter, which among others, includes a secrets like inSensitive.t.sensitive.userAuth

**Comment by khanhnt93** [comment]
Thank danglus, I got it. But I have some confused about key in TPM.
1. Is any way to use a key in other computers?
2. In test code, I just found CreatePrimary object by password, can I create primary by policy and hmac?
3. Can TPM generate pair keys and give user without encrypted. I just want to generate key feature of TPM.
Thank you!

**Comment by danglus** [comment]
1) Primary keys are unique to a specific TPM (The primary keys are derived from the TPM seed). However, it is possible to duplicate regular keys to other TPMs.
2) I have never tried a primary key with policy, but it should work, but why? what kind of policy do you need for the primary key?
3) I'm not aware of a way to do it. However, using a TPM generated random number as an input to a KDF running on the host would, probably, have the same effect.

**Comment by khanhnt93** [comment]
About question 2, because I found example use policy in define nvindex, so I'm try to use policy for other case, I choose create primary object :D. TPM key can use with digital signatures (smart card), ... by use policy, so I'm try to use policy and if I complete I will find to use smart card with tpm. Do you know in my case, how do people do?
