### ISSUE TITLE
Use TPM2_PolicyAuthorize to change policy in case BIOS update

### ISSUE THREAD

**Issue by khanhnt93** [01org/tpm2-tss#487]
I'm trying to test full disk ecryption with TPM. I read in "A Practical Guild to TPM 2.0" that example "A Policy for Flexible PCRs". It's mean change authorization value of NVIndex (that contain full disk encryption key) with new PCR state. They said I must use TPM2_PolicyAuthorize to build that flexiable policy. I complete confused how to use this function. Can you tell me follow function to:
- Create NVIndex contain full disk key encryption with policy use PCRs state
- Change autorization value of NVIndex with new PCRs state (in case update BIOS)

Thank you!

**Comment by danglus** [comment]
Yes, it is unfortunate that the practical guide, does not include code that can actually compile. 
Anyway, I have only used TPM2_PolicyAuthorize with keys (and not in NV).  The idea is that,  regardless of the policy that you create, if you add TPM2_PolicyAuthorize at the end, the final policy digest will be the same.
So, if you create a key/NV with that final policy-digest, you'll be able to use it with multiple policies.
TPM2_PolicyAuthorize validates that the new policy digest (before you issue TPM2_PolicyAuthorize) was properly signed with the right key (The key name, influence the final policy digest).
In your case, it should allow you to sign policies with different PCR values in TPM2_PolicyPCR and use them with the same NV.

 Does it makes sense?

**Comment by khanhnt93** [comment]
Hi Danglus,
Thank you for your reply.
But  I still do not understand clearly. I add some assumption which I understand below:
1. For create NVIndex with PCR:
- Use PolicyPCR to get policy digest from PCR
- Use PolicyAuthorize here. But I do not understand how to and why use PolicyAuthorize here. 
- Use NVDefine to create NVIndex with that policy digest.
2. For change autorization value of NVIndex:
- Use PolicyPCR to get new policy digest from PCR
- Use PolicyAuthorize here. But I do not understand how to and why use PolicyAuthorize here. 
- Use NVChangeAuth to change autorization value of NVIndex.
Could you plz explain it more details as the flow?
Thank you so much.

**Comment by danglus** [comment]
Not exactly:
 
   In high level:

1)  For creating the NVIndex:
  * Create a key that will be used for signing future policies (Maybe you want to do it in the management system)
   * start a trial policy
   * Issue a PolicyAuthorize command: call it with the key name (there is some annoying staff that you should do with policyRef that I'll omit for the moment)
    * use the policy digest to create the NVIndex

2) Now you have to create and sign the and actual policy for the NVINDEX, most likely, you would do this step in the management system
    * start a trial policy
    * use PolicyPCR with the PCR value
    * Sign the digest with the key
   
3) Verify the policy (in the destination system)
    * verify the sigature of the digest with the key (theoretically, only the public area is needed) and get a validation ticket.

4) To load the policy:
     * start a policy
     * use PolicyPCR with the PCR value (now it will actually compare the PCR value)
     * Issue a PolicyAuthorize with the validation ticket and the signed-digest. if the signed-digest equals to the current policy digest and the ticket is valid. The command will pass and the policy digest will be changed to the digest in #1 
     * Now you have a policy handle that can be used with the NVINDEX

**Comment by khanhnt93** [comment]
In #1, function PolicyAuthorize return for caller policy disgest that policy disgest use to create nvindex, what are things PolicyAuthorize base on to calculator digest?
In #4, I think PolicyAuthorize must receive all things in #1 to general policy digest in #1 again, is that right?
Final, can you give me the code that you implement PolicyAuthorize?
Thank you!

**Comment by danglus** [comment]
One of the inputs to PolicyAuthorize is:
"TPMT_TK_VERIFIED checkTicket // ticket validating that approvedPolicy and policyRef were signed by keySign"

This ticket is produced by Tss2_Sys_VerifySignature - which you must run before. One of the command's input is the handle of the keySign. In theory, only loading the public section should be enough. 

I think that PolicyAuthorize is using a ticket rather than verifying the signature by its on in order to improve performance. This way, you can verify the ticket once, and then use the ticket multiple times.

(regarding code sharing, let me think about it, I have a simple project that I use for prototyping , maybe I'll simply upload the whole thing to github)

  Cheers!
Dan

**Comment by khanhnt93** [comment]
I mean in #1, just need keySign pass to PolicyAuthorize. If I am a attacker, I just pass keySign to PolicyAuthorize to get policyDigest and use it to read NVIndex? Is it right?

**Comment by danglus** [comment]
No, a trial session can't be use for authorization.

**Comment by khanhnt93** [comment]
I got it, I read session life cycle but I don't remeber :D. 
Thank you for your help!

**Comment by Nilesh-Deshmukh** [comment]
Hi ,

I have just started learning the TPM2 world, and really amazed by "TPM2_PolicyAuthorize" tackle the PCR brittleness.
I have understood the above discussion but not sure how to user TRAIL session for "TPM2_PolicyAuthorize"
Please share the sample if anyone has..

Thanks and Regards,
Nilesh

**Comment by Nilesh-Deshmukh** [comment]
Hi Khanhnt;

I want to understand the flow(sample code/example) when the TPM2_PolicyAuthorize used in the trial session to create nvindex and  TPM2_PolicyAuthorize used for authorization.

As you described above I understand the concept but not able to find any complete reference working example to tackle the PCR brittleness. I believed that TPM2 has introduced the TPM2_PolicyAuthorize to tackled the brittleness problem (which was in TPM1.2).

**Comment by khanhnt93** [comment]
I think you can read example TestPolicy() in https://github.com/tpm2-software/tpm2-tss/blob/master/test/tpmclient/tpmclient.int.c to understand about using policy. Although it has not example for TPM2_PolicyAuthorize but I think you can use TPM2_PolicyAuthorize if you understand using policy in TPM.
About tackled the brittleness problem, I don't know about it (I don't learn about TPM1.2). Can you describe more about it?

**Comment by Nilesh-Deshmukh** [comment]
if keys or data are locked to a PCR that represents the BIOS of a system, it’s tricky to upgrade the BIOS. This is PCR fragility. Typically, before a BIOS upgrade was performed on TPM 1.2 systems, all secrets locked to PCR 0, for example (which represents the BIOS), had to be unsealed and then resealed after the upgrade was done. This is both a manageability nightmare and a nuisance to users.
 In the TPM 2.0 specification, you can seal things to a PCR value approved by a particular signer instead of to a particular PCR value (although this can still be done if you wish). That is, you can have the TPM release a secret only if PCRs are in a state approved (via a digital signature) by a particular authority.

You can read more about it in "PracticalGuideTPM2" book

**Comment by khanhnt93** [comment]
I have read that book. PolicyAuthorize will solve that problem. It base on a pair public, private key to manage trust PCR value. If PCR value change (in case BIOS update), we just need to sign to new PCR value.

**Comment by bzhu5** [comment]
@danglus 
I had the same issue and request/requirement, you mentioned that you might publicize your sample code of how to use PolicyAuthorize, so what's the status now? 

really appreciate that you (or someone else) can share the sample code or contribute this to this project.

thanks

Bing

**Comment by williamcroberts** [comment]
> @danglus <https://github.com/danglus>
> I had the same issue and request/requirement, you mentioned that you might
> publicize your sample code of how to use PolicyAuthorize, so what's the status
> now?
> 
> really appreciate that you (or someone else) can share the sample code or
> contribute this to this project.
> 
tpm2-tools project has this command:
https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_policyauthorize.c

That should make decent example code.
