### ISSUE TITLE
tpm2-tools-2.1.0 and tpm_server (ibmtpm974)

### ISSUE THREAD

**Issue by tomaszpr** [01org/tpm2-tss#526]
I'm not sure where the problem is (tpm_server, tpm2-tss, tpm2-tools or tpm2-abrmd).
That's why I put link to this issue created by me.

[tpm2-tools-2.1.0 and tpm_server (ibmtpm974)](https://github.com/01org/tpm2-tools/issues/469)

If it's wrong location please close issue. Sorry for that.

**Comment by flihp** [comment]
Lost track of this one. It was resolved in the TSS some time back. It's also resolved in the tools.
