### ISSUE TITLE
Missing resourcemgr

### ISSUE THREAD

**Issue by meesern** [01org/tpm2-tss#552]
When I build tpm2-tss on a Raspberry Pi 3 using the process

    ./bootstrap
    ./cofigure
    make
The process completes without errors but I find no file or directory `resourcemgr` which I understand to be necessary for accessing the TPM via tpm2_tools.  The directory `resourcemgr` which I presumed was going to be created by the build process does not exist.

**Comment by danglus** [comment]
The tpm2_tools supports the  "-T device"  flag which instructs the tool to connect directly to the TPM driver (it must be run with 'sudo').

resourcemgr was replaced by an independent project: https://github.com/01org/tpm2-abrmd/

  Regards,
Dan

**Comment by martinezjavier** [comment]
@meesern to expand on @danglus' answer, there is also a in-kernel resource manager. In that case you don't need a user-space resource manager.

So you could use the device TCTI (e.g: -T device or set the TPM2TOOLS_TCTI_NAME=device env var) but access a /dev/tpmrmX character device instead of a /dev/tpmX one (e.g: -T device:/dev/tpmrm0 or also set TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0). But this support is quite recent, so at least a v4.12 kernel is needed.

**Comment by meesern** [comment]
Ah thank you.  If I understand correctly the resource manager `resourcemgr` is now removed and replaced by `tpm2-abrmd` binary built from the tpm2-abrmd repository.  

But if I have linyux kernel v4.12 or greater then I don't need to run a separate resource manager because I can use the -T option on tss2-tools (typically with /dev/tpmrm0).  

However I'm still not sure if I need tpm2-abrmd with an older kernel.
I have a 4.4 kernel with /dev/tpm0 present but no /dev/tpmrm0.

When I use 

    sudo tpm2_pcrlist -T /dev/tpm0
I get

    ERROR: Unknown tcti, got: "/dev/tpm0"

Is this expected (when not running a resource manager)?

I may have other problems because on my system `sudo tpm2-abrmd` returns without output and without leaving a running process. I.e. appears to do nothing.

   sudo cat /dev/tpm0 
returns without output (on the command line).  Could anyone say if this is expected behavior?

**Comment by martinezjavier** [comment]
@meesern if you have an older kernel (< 4.12) then you need a resource manager. Which as you said is tpm2-abrmd now.

Your command is not correct, it should be:

```
$ sudo tpm2_pcrlist -T device:/dev/tpm0
```

Although the :/devtpm0 is not needed since that's the default, I just included for completeness.

Did you install the tpm2-abrmd or starting from the build directory? I could start it with:

```
$ sudo -u tss ./src/tpm2-abrmd
```

I believe the behaviour is expected. If you read the character device but without writing a TPM command before, it's not supposed to return anything AFAIK.

**Comment by martinezjavier** [comment]
@meesern BTW, can you please close this issue and we can move the conversation to the [tpm2 mailing list](https://lists.01.org/mailman/listinfo/tpm2)?

This is not really an issue with the tpm2-{tss,tools} but more with your environment / setup.

**Comment by danglus** [comment]
@martinezjavier 
  A quick question: Is the in-kernel resource manager part of the tpm2-abrmd project?

(Disclaimer: I haven't tried tpm2-abrmd, my application is working directly over the driver)

**Comment by meesern** [comment]
Thank you 

    sudo tpm2_pcrlist -T device:/dev/tpm0

does return a list of (zero) PCR registers.

Yes, I'll close the issue,   But it is worth raising here as existing/older documents refer to `resourcemgr` and there is no documentation to say that it has disappeared/moved or is no longer necessary.   The README.md in this repo still refers to `resourcemgr` for example.

**Comment by martinezjavier** [comment]
@meesern agreed. Feel free to file a new issue about the docs been outdated and still referencing the old resource manager.

**Comment by williamcroberts** [comment]
@danglus the in-kernel RM and tpm2-abrmd are 100% separate projects. They share nothing.

**Comment by williamcroberts** [comment]
@meesern You can also chown `/dev/tpm0` to your shell user, or set up the dac perms in some way your user can access it. This way you're not running things with root permissions.

I have no idea what perms distor's  are assigning to /dev/tpm0 and there is some supplemental group you should be adding to your shells. Assuming there isn't...

I would recommend this:
```
sudo chgrp $USER /dev/tpm0
sudo chmod g+rw /dev/tpm0

# note no sudo for any tpm2_<command>'s from here on out
tpm2_pcrlist -T device:/dev/tpm0
```
You can even export the TCTI so you don't need to specify -T:
```
export TPM2TOOLS_TCTI_NAME=device
export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0

# no need for -T passed here unless you want to change TCTIs
tpm2_pcrlist
```

**Comment by danglus** [comment]
@williamcroberts , one last question, is the in-kernel RM part of this project? (TPM2.0-TSS)
   If not, can you share a pointer to it?

**Comment by martinezjavier** [comment]
@danglus no, the in-kernel RM isn't part of this project. The code is in the upstream Linux kernel (starting from v4.12).

The actual commit in Linux that added the support is [745b361e989a](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=745b361e989a) ("tpm: infrastructure for TPM spaces") and commit [fdc915f7f719](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fdc915f7f719) ("tpm: expose spaces via a device link /dev/tpmrm<n>") exposed to user-space through a new character device (/dev/tpmrmX).

**Comment by williamcroberts** [comment]
@danglus it's maintained here by Jarrko:
https://sourceforge.net/p/tpmdd/mailman/tpmdd-devel/

FYI source forge seems down
