### ISSUE TITLE
Bitlocker equivalent for Linux

### ISSUE THREAD

**Issue by danglus** [01org/tpm2-tss#553]
Hi,
  Is there a Linux equivalent to Microsoft Bitlocker? 
Bitlocker is a HDD encryption tool which use TPM1.2 for protecting the encryption password (https://technet.microsoft.com/en-us/library/cc732774(v=ws.11).aspx

  Thanks,
Dan

**Comment by webmeister** [comment]
For TPM 1.2, there were several attempts, e.g. https://github.com/fox-it/linux-luks-tpm-boot

For TPM 2.0, there were some discussions on the mailing list: https://lists.01.org/pipermail/tpm2/2017-July/000015.html

**Comment by martinezjavier** [comment]
@danglus as @webmeister pointed out in that email thread, we want to add support for the Clevis project to automatically unlock LUKS volumes using a TPM2.

If you are interested, the pull request that adds the feature is [here](https://github.com/latchset/clevis/pull/17). It would be great if you can give it a try and provide your feedback.

Please let me know if you need any information on that TPM2 support or Clevis in general.

**Comment by martinezjavier** [comment]
@danglus could you please close this since is not related to a tpm2-tss issue? If you have any further questions about this topic, we can move the conversation to the [tpm2 mailing list](https://lists.01.org/mailman/listinfo/tpm2).
